Repository openSUSE/osem, pull requests merged in 2019-05, with the labels that each got.

#2512 Fix incorrect format in xml dates
  app/views/schedules/show.xml.haml
Labels: bug :bug:

#2508 Document roles:add rake task in update from 1.0
  CHANGES.md
Labels: bug :bug:, documentation :page_facing_up:

#2519 Update devise_ichain_authenticatable to 0.3.2
  Gemfile.lock
Labels: P1

#2518 Point to Giggity from the schedule page
  .haml-lint_todo.yml
  Gemfile
  app/controllers/schedules_controller.rb
  app/views/schedules/_qr_code_modal.html.haml
  app/views/schedules/show.html.haml
Labels: feature :bulb:
