Repository openSUSE/osem, pull requests merged in 2019-03, with the labels that each got.

#2407 Update typo in contribution guide
  CONTRIBUTING.md
Labels: documentation :page_facing_up:

#2390 Various update fixes
  CHANGES.md
  app/models/ability.rb
  app/views/admin/versions/_object_desc_and_link.html.haml
  lib/tasks/several_schedules.rake
  lib/tasks/version.rake
Labels: P1, bug :bug:, documentation :page_facing_up:, production

#2391 Remove picktime
  app/assets/javascripts/osem-datepickers.js
  spec/features/conference_spec.rb
Labels: bug :bug:

#2435 Fix flickering submit valid proposal test
  spec/features/proposals_spec.rb
Labels: test suite :syringe:

#2436 Store screenshot when feature test fails
  spec/support/save_feature_failures.rb
Labels: test suite :syringe:
