Repository openSUSE/osem, pull requests merged in 2019-07, with the labels that each got.

#2548 Update selenium-webdriver
  .travis.yml
  Dockerfile.base
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: P1, research :male_detective:

#2437 Disable capybara animation
  spec/spec_helper.rb
Labels: test suite :syringe:

#2558 Update schema.rb formatting
  db/schema.rb
Labels: GSoC

#2535 Invitation for booth responsibles
  Gemfile
  Gemfile.lock
  app/controllers/admin/booths_controller.rb
  app/controllers/application_controller.rb
  app/controllers/booths_controller.rb
  app/controllers/concerns/invitation.rb
  app/models/booth.rb
  app/models/user.rb
  app/views/booths/_form.html.haml
  app/views/devise/invitations/edit.html.haml
  app/views/devise/mailer/invitation_instructions.html.erb
  app/views/devise/mailer/invitation_instructions.text.erb
  config/initializers/devise.rb
  config/locales/devise_invitable.en.yml
  db/migrate/20190603143107_devise_invitable_add_to_users.rb
  db/schema.rb
  spec/controllers/admin/booths_controller_spec.rb
  spec/controllers/booths_controller_spec.rb
  spec/factories/booths.rb
Labels: GSoC
